-- hyprdark — Hyprland config (Lua, Hyprland ≥ 0.55)
-- Each require() runs in its own scope: an error in one module pops a
-- notification but does not take down the rest of the config.

require("conf/env")
require("conf/look")
require("conf/input")
require("conf/windowrules")
require("conf/keybindings")
require("conf/autostart")

-- monitors (generated by scripts/setup-display.sh; safe to hand-edit)
local ok_m = pcall(require, "monitors")
if not ok_m then
    -- fallback until you run setup-display.sh
    hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
end

-- machine-specific (generated by the installer: lid switch, NVIDIA)
pcall(require, "machine")
