-- hyprdark — Hyprland config (Lua, Hyprland ≥ 0.55)
-- Each require() runs in its own scope: an error in one module pops a
-- notification but does not take down the rest of the config.

require("conf/env")
require("conf/look")
require("conf/input")
require("conf/windowrules")
require("conf/keybindings")
require("conf/autostart")

-- machine-specific (generated by the installer: monitors, lid switch, NVIDIA)
local ok = pcall(require, "machine")
if not ok then
    -- no machine.lua yet — sane monitor default so the session still starts
    pcall(hl.monitor, { output = "", mode = "preferred", position = "auto", scale = 1 })
end
